### PR TITLE
WebChucK IDE 2.1.4

### PR DESCRIPTION
**Pull request by terryzfeng**
## Changes:
- Export ChucK/WebChucK now has a descriptive .zip name
- Improved WebChucK export modal interface and usage
- Added GUI and Visualizer help prompts
- Added "About IDE" under help for version info
- Playing a shred now has green ANSI message (like miniAudicle)
- New WebChucK sensors `Gyro` & `Accel` (thanks @mulshine)
- Added notification pings for examples (GUI, HID, Sensor)
- minor UI tweaks, bug fixes, and improvements

### CODE REVIEW

**Comment by terryzfeng** [comment]
@mulshine I just added the Gyro and Accel to the IDE! These are all under a new Sensor tab and you can find the examples in the dropdown. Please test it out and I'd love to hear how it goes!

So far, it's working here and a lot of fun~

test: https://ccrma.stanford.edu/~tzfeng/webchuck-ide/

**Comment by mulshine** [comment]
Awesome! 

1) I like the addition of the sine waves for the demos - makes the effect more noticeable!

2) I was confused at first about how to enable the gyro/accelerometer in the Sensor settings. I wonder about (for at least the two demo examples) prompting the user when those examples are loaded (before the program runs). In other custom code, users will (by then) know where to enable gyro/accel. (Alternatively, code parsing for "Accel"/"Gyro" objects and when the shred is added, we prompt if necessary). 

3) If I leave the browser / lock my phone, then return, neither demo makes sound anymore, and time doesn't pass in the remaining shred. I also can't remove or add a shred. Fixed by refreshing page. This happens even with HelloSine, so I think it's a WebChucK IDE issue that you may already be aware of. How do you think we could resolve this? I think we'd need to do the opposite of "Start WebChucK" when the browser context is lost (e.g. Stop WebChucK), remove all shreds, and likely just need to have the user start it again. I don't see another way around it really, unless when the browser context is gained back we just need to do another theChucK.audioContext.resume() call?? That might be it actually... 

4) Feels like a little more latency than outside the IDE (e.g. mikemulshine.com/accel). Is it just the IDE overhead?

Otherwise I think it's pretty good to go :)

**Comment by terryzfeng** [comment]
1. Haha I didn't change the examples, that's just your code :D 
2. I think it's possible to add a dot or something when loading an example! I can try that out if it's easy!
3. Interesting. On Android, the sound just continues (although crackles cause background thread). I haven't run into this issue yet. If you'd like to file an issue perhaps? @mulshine 
4. Oof, I hope it's not too bad. Maybe turning off logging could make it faster? But I do notice from time to time that the IDE could be faster...

I'll try to tackle 2 and hopefully we can kick the can down the road... :)

**Comment by terryzfeng** [comment]
2 done :)

**Comment by mulshine** [comment]
Thanks @terryzfeng :) 
1) Ahh my bad! I don't know why it felt different for me in the IDE. Might have just been the latency. 
2) Probably not highest priority. 
3) I will file an issue. 
4) Yeah, maybe we can at least have an option to toggle on/off logging (of all sorts?) to improve latency? Should this be another issue?

**Comment by mulshine** [comment]
I think otherwise good to merge!  @terryzfeng

**Review by mulshine — APPROVED** [review]
Looks good to me.

**Comment by terryzfeng** [comment]
Thanks Mike! I can file an issue for turning off logging! The notification pings work great! Thanks for the suggestion!

**Pull request merged**
